FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:2.1.0-gpu-py310-cu121-ubuntu20.04-ec2

RUN pip install --upgrade pip
RUN pip uninstall -y fastai

RUN apt update && apt install -y tmux screen

ARG WORKSPACE
WORKDIR ${WORKSPACE}

COPY . .
RUN pip install -r requirements.txt

ENTRYPOINT []
